version: 2.1
workflows:
  main:
    jobs:
      - test:
          name: test_node_10
          node_version: 10.11.0
      - build:
          name: build_node_10
          node_version: 10.11.0
          filters:
            branches:
              only: master
      - deploy:
          name: deploy_node_10
          filters:
            branches:
              only: master
          requires:
            - test_node_10
            - build_node_10

executors:
  default:
    parameters: &node_version_parameters
      node_version:
        type: enum
        enum: ["10.11.0", "8.12.0", "6.14.4"]
    working_directory: ~/workspace
    docker:
      - image: circleci/node:<< parameters.node_version >>
  awscli:
    docker:
      - image: cdssnc/aws-cli
    working_directory: ~/workspace

jobs:
  test:
    parameters: *node_version_parameters
    executor:
      name: default
      node_version: << parameters.node_version >>
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-dependencies-{{ .Branch }}-
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: v1-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Check diff (yarn.lock)
          command: git diff --exit-code
      - run:
          name: Run Test
          command: yarn test
  build:
    parameters: *node_version_parameters
    executor:
      name: default
      node_version: << parameters.node_version >>
    steps:
      - checkout
      - run: yarn
      - run:
          name: Run Build
          command: yarn build
      - persist_to_workspace:
          root: .
          paths: dist
  deploy:
    executor:
      name: awscli
    steps:
      - attach_workspace:
          at: dist
      - run: aws configure set aws_access_key_id ${AWS_ACCESS_KEY}
      - run: aws configure set aws_secret_access_key ${AWS_SECRET_KEY}
      - run: aws configure set default.region ap-northeast-1
      - run:
          name: Run Deploy
          command: yarn deploy
